# Generated by Django 4.0.4 on 2022-05-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_rgscode_options_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgscode',
            name='phone_number',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
