# Generated by Django 4.0.4 on 2022-05-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_rgscode_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgscode',
            name='code',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='rgscode',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
